"""empty message

Revision ID: 090c86c407ee
Revises: eb2ed2d80473
Create Date: 2020-05-17 22:48:59.889623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090c86c407ee'
down_revision = 'eb2ed2d80473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_member_to_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigned_member_to_shift')
    # ### end Alembic commands ###
