"""added run summary model

Revision ID: 1ac26741acf4
Revises: 5be61399a8a5
Create Date: 2020-07-17 17:29:27.179055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac26741acf4'
down_revision = '5be61399a8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.String(length=64), nullable=True),
    sa.Column('shift', sa.String(length=64), nullable=True),
    sa.Column('blank_lot', sa.String(length=64), nullable=True),
    sa.Column('pc_lot', sa.String(length=64), nullable=True),
    sa.Column('sample_dispensing', sa.String(length=64), nullable=True),
    sa.Column('verifier', sa.String(length=64), nullable=True),
    sa.Column('dispensing_start', sa.DateTime(), nullable=True),
    sa.Column('dispensing_finish', sa.DateTime(), nullable=True),
    sa.Column('sample_qty', sa.Integer(), nullable=True),
    sa.Column('extraction_rgt_lot', sa.String(length=64), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('plate_load_time', sa.DateTime(), nullable=True),
    sa.Column('mlb_load_time', sa.DateTime(), nullable=True),
    sa.Column('qpcr_mix_lot', sa.String(length=64), nullable=True),
    sa.Column('mgisp_tips_lot', sa.String(length=64), nullable=True),
    sa.Column('machine_operator', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_summary')
    # ### end Alembic commands ###
