"""empty message

Revision ID: 36ada14cfef2
Revises: 090c86c407ee
Create Date: 2020-05-18 00:04:28.697105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ada14cfef2'
down_revision = '090c86c407ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_samples', 'shift')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_samples', sa.Column('shift', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
