"""empty message

Revision ID: 5be61399a8a5
Revises: 
Create Date: 2020-07-02 11:11:27.167608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be61399a8a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('machine_certified', sa.Boolean(create_constraint=128), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=True)
    op.create_table('retests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=True),
    sa.Column('plate_id', sa.String(length=64), nullable=True),
    sa.Column('well', sa.String(length=32), nullable=True),
    sa.Column('fam', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vic', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('analyst', sa.String(length=64), nullable=True),
    sa.Column('retest_type', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('remarks', sa.String(length=512), nullable=True),
    sa.Column('admin_comment', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('assignments', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('verified', sa.Boolean(create_constraint=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('assigned_member_to_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assigned_member_to_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_samples')
    op.drop_table('assigned_member_to_stations')
    op.drop_table('assigned_member_to_shift')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_table('station')
    op.drop_table('shift')
    op.drop_table('retests')
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
