"""added retests model

Revision ID: c0ba34cb2a0d
Revises: 36ada14cfef2
Create Date: 2020-06-26 04:26:28.447169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ba34cb2a0d'
down_revision = '36ada14cfef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=True),
    sa.Column('plate_id', sa.String(length=64), nullable=True),
    sa.Column('well', sa.String(length=32), nullable=True),
    sa.Column('fam', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vic', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('analyst', sa.String(length=32), nullable=True),
    sa.Column('retest_type', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('remarks', sa.String(length=512), nullable=True),
    sa.Column('admin_comment', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retests')
    # ### end Alembic commands ###
